# Generated by Django 5.1.6 on 2025-03-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_flight_availableseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='ArrivalAirport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='DepartureAirport',
        ),
        migrations.AddField(
            model_name='flight',
            name='ArrivalCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='bookings.city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='DepartureCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='bookings.city'),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
