# Generated by Django 5.1.6 on 2025-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_city_remove_flight_arrivalairport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
