# Generated by Django 5.1.6 on 2025-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_flight_availableseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='AvailableSeats',
            field=models.IntegerField(default=126),
        ),
    ]
