# Generated by Django 5.1.6 on 2025-03-15 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_flight_availableseats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='IsBooked',
        ),
        migrations.AddField(
            model_name='seat',
            name='Class',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserTicket',
        ),
    ]
