# Generated by Django 5.1.6 on 2025-03-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_user_seat_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='UserID',
            new_name='User',
        ),
    ]
