# Generated by Django 5.1.6 on 2025-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_rename_userid_seat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Price',
        ),
        migrations.AddField(
            model_name='seat',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
